print(paste("Enter the First matrix : "))
v1<-scan()
m1<-array(c(v1),dim = c(4,4,1))
print(m1)
m2=apply(m1,2,rev)
m2=array(c(m2),dim=c(4,4,1))
print(m2)
a1=sum(diag(apply(m2,2,rev)))
print(paste("Sum of Diagonal Elements is : ",a1))
a2=sum(diag(apply(m1,2,rev)))
print(paste("Sum of Anti-Diagonal Elements is : ",a2))
